name: popmark
description: A command-line program that populates your markdown files with the output of documented code segments.
version: 0.2.0
homepage: https://github.com/ram6ler/popmark

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  popmark: 0.2.0

dependencies:
  args: ^2.4.2




