name: popmark
description: A command-line program that populates your markdown files with the output of documented code segments.
version: 0.1.0
# homepage: https://www.example.com
# author: Richard Ambler <rambler@ibwya.net>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.2

dev_dependencies:
  pedantic: ^1.8.0
